-- Section A: Revenue performance

-- Total revenue generated from won opportunities
SELECT
ROUND(SUM(close_value),2) AS total_revenue
FROM sales_pipeline_cleaned
WHERE deal_stage = 'Won';

-- Revenue by product

SELECT product,
ROUND(SUM(close_value),2) AS revenue
FROM sales_pipeline_cleaned
WHERE deal_stage = 'Won'
GROUP BY product
ORDER BY revenue DESC;

-- Section B: Product performance

/* Analyze product performance using deal volume, 
revenue contribution and average deal size. */

	SELECT product,
COUNT(opportunity_id) AS won_deals,
ROUND(SUM(close_value),2) AS revenue,
ROUND(AVG(close_value),2) AS avg_deal_size
FROM sales_pipeline_cleaned
WHERE deal_stage = 'Won'
GROUP BY product
ORDER BY revenue DESC;

-- Revenue generated by customer sector

SELECT 
a.sector, 
SUM(sp.close_value) AS revenue
FROM sales_pipeline_cleaned sp
LEFT JOIN accounts a ON sp.account = a.account
WHERE sp.deal_stage = 'Won'
GROUP BY a.sector
ORDER BY revenue DESC;

-- Top sales agents by revenue

SELECT sales_agent,
SUM(close_value) AS revenue
FROM sales_pipeline_cleaned
WHERE deal_stage = 'Won'
GROUP BY sales_agent
ORDER BY revenue DESC;